### ISSUE TITLE
Unable to override port in add-on

### ISSUE THREAD

**Issue by Minims** [yukulehe/gazpar2mqtt#13]
Unable to override and convert new port to integer

config
```
MQTT_HOST: '192.168.1.10'
MQTT_PORT: 1883
```

addon log
```
MQTT_HOST="192.168.1.10"
MQTT_PORT="1883"
..
2021-11-18 22:38:05,810 Welcome to gazpar2mqtt
2021-11-18 22:38:05,810 -----------------------------------------------------------
2021-11-18 22:38:05,810 -----------------------------------------------------------
Traceback (most recent call last):
  File "/app/gazpar2mqtt.py", line 742, in <module>
    params = _getEnvParams()
  File "/app/gazpar2mqtt.py", line 107, in _getEnvParams
    params["mqtt", "port"] = int(os.environ["MQTT_PORT"])
ValueError: invalid literal for int() with base 10: '"1883"'
[22:38:05] FATAL: The app has crashed. Are you sure you entered the correct config options?
``

**Comment by goldendatahub** [comment]
Problème lié à l'issue #11 
J'ai ajouté un bout de code pour retirer d'éventuelles quotes dans la chaine de caractère.
Fix prévu en release 0.4.3
