### ISSUE TITLE
Get Measurements error

### ISSUE THREAD

**Issue by kalw** [yukulehe/gazpar2mqtt#33]
Hello !

I semble qu'il y ai encore un petit souci de recuperation des données :)
Comment peu t on aider ? 

``` 
2021-12-06 08:10:46,984 1 PCE found !
2021-12-06 08:10:46,986 Get measures of PCE xxx alias xxx
2021-12-06 08:10:46,986 Range period : from 2021-11-29 to 2021-12-05...
2021-12-06 08:10:47,050 https://monespace.grdf.fr:443 "GET /api/e-conso/pce/consommation/informatives?dateDebut=2021-11-29&dateFin=2021-12-05&pceList%5B%5D=xxx HTTP/1.1" 200 None
Traceback (most recent call last):
  File "/app/gazpar2mqtt.py", line 353, in <module>
    run(myParams)
  File "/app/gazpar2mqtt.py", line 146, in run
    myGrdf.getPceDailyMeasures(pce,startDate,endDate)
  File "/app/gazpar.py", line 177, in getPceDailyMeasures
    for measure in measureList[pce.pceId]["releves"]:
TypeError: list indices must be integers or slices, not str
The app has crashed. Are you sure you entered the correct config options?
```

**Comment by goldendatahub** [comment]
Hello, je regarde

**Comment by goldendatahub** [comment]
En relançant le script ça refonctionne. Y'avait peut être un souci sur le site GRDF autour de 8h du mat ce matin.
En tout cas merci pour ton retour, je vais blinder le code pour gérer les retours anormaux de l'API GRDF.

**Comment by goldendatahub** [comment]
@kalw Préviens moi si de ton côté ça refonctionne

**Comment by goldendatahub** [comment]
Je comprends que ça refonctionne.

**Comment by kalw** [comment]
je confirme, top merci pour la reactivité !
