### ISSUE TITLE
Erreur de sélection  plage de dates

### ISSUE THREAD

**Issue by DamGranger** [yukulehe/gazpar2mqtt#40]
Il semble que gazpar2mqtt récupère désormais une date d'activation du PCE et s'en sert de borne inférieure pour la récupération des données. Or si cette date a plus de 3 ans, l'API e-conso renvoie une erreur :
`{"code":400,"message":"Bad Request"}`

On retrouve cette erreur dans le journal :
```
2021-12-11 23:30:59,804 INFO Get measures of PCE xxxxxxxxxxxxxxx alias xxxxxxxxxxxxxxx
2021-12-11 23:30:59,804 INFO ---------------------------------
2021-12-11 23:30:59,804 INFO PCE activation date : 2017-09-05
2021-12-11 23:30:59,805 INFO Range period : from 2017-09-05 to 2021-12-11...
2021-12-11 23:30:59,859 DEBUG https://monespace.grdf.fr:443 "GET /api/e-conso/pce/consommation/informatives?dateDebut=2017-09-05&dateFin=2021-12-11&pceList%5B%5D=xxxxxxxxxxxxxxxxx HTTP/1.1" 400 None
Traceback (most recent call last):
  File "/app/gazpar2mqtt.py", line 583, in <module>
    run(myParams)
  File "/app/gazpar2mqtt.py", line 215, in run
    myGrdf.getPceDailyMeasures(myPce,startDate,endDate)
  File "/app/gazpar.py", line 253, in getPceDailyMeasures
    for measure in measureList[pce.pceId]["releves"]:
KeyError: 'xxxxxxxxxxxxxxxxx'
The app has crashed. Are you sure you entered the correct config options?
```
A ce jour l'API e-conso fonctionne si je met 2018-12-11 en borne inférieure, mais pas 2018-12-10. Il faudrait donc définir au maximum dateFin - 3 ans comme dateDebut quand le PCE activation date est avant cette date.

**Comment by DamGranger** [comment]
Le problème apparaît semble-t-il dans ce commit : https://github.com/yukulehe/gazpar2mqtt/commit/78c231a5ac3018560206fb014b5e38a56a58c996

**Comment by goldendatahub** [comment]
Hello. Ok je rectifie.

**Comment by goldendatahub** [comment]
Poussé en 0.6.1

**Comment by DamGranger** [comment]
```
2021-12-13 00:27:52,097 INFO PCE activation date : 2017-09-05
Traceback (most recent call last):
  File "/app/gazpar2mqtt.py", line 587, in <module>
    run(myParams)
  File "/app/gazpar2mqtt.py", line 214, in run
    startDate = minDate.date()
NameError: name 'minDate' is not defined
The app has crashed. Are you sure you entered the correct config options?
```

Ligne 214 de gazpar2mqtt.py :
`startDate = minDate.date()`
A remplacer par :
`startDate = minDateTime.date()`
