### ISSUE TITLE
Follow-up #40 : erreur si date d'activation supérieure à 3 ans

### ISSUE THREAD

**Issue by DamGranger** [yukulehe/gazpar2mqtt#42]
Follow up #40 
```
2021-12-13 00:27:52,097 INFO PCE activation date : 2017-09-05
Traceback (most recent call last):
  File "/app/gazpar2mqtt.py", line 587, in <module>
    run(myParams)
  File "/app/gazpar2mqtt.py", line 214, in run
    startDate = minDate.date()
NameError: name 'minDate' is not defined
The app has crashed. Are you sure you entered the correct config options?
```

Ligne 214 de gazpar2mqtt.py :
`startDate = minDate.date()`
A remplacer par :
`startDate = minDateTime.date()`

**Comment by goldendatahub** [comment]
Argh, désolé. Je corrige dans le main.

**Comment by DamGranger** [comment]
Correction OK
